[package]
name = "eink-eventbus"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anymap = "0.12.1"
log = "0.4.17"
rand = "0.8.5"
parking_lot = "0.12.1"
hex = "0.4.3"