imports_layout = "Vertical"
imports_granularity = "Item"
# imports_granularity = Module
brace_style = "AlwaysNextLine"
struct_lit_single_line = true
reorder_imports = true
max_width = 100
merge_imports = true
