[package]
name = "eink-logger"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
debug-view-logger = { git = "http://git2.ensurebit.net/lenovo-thinkbook-gen4/debug-view-logger.git" }
