[package]
name = "eink-composer-lib"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
base64 = "*"
base64-serde = "*"
# ipc-channel = "0.16"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "*"
serde_json = "*"
# ipmpsc = "0.5.1"
# interprocess = "1.1.1"
bincode = "1.3.3"
nng = "*"

# [dependencies.zenoh]
# git = "https://github.com/eclipse-zenoh/zenoh"
# rev = "45b7ad7"
# features = ["shared-memory"]


[dependencies.windows]
version = "0.39.0"
features = [
    "interface",
    "implement",
    "Foundation",
    "Foundation_Numerics",
    "Foundation_Collections",
    "Win32_Foundation",
    "Win32_Devices_Display",
    "Win32_System",
    "Win32_System_WinRT",
    "Win32_System_WinRT_Display",
    "Win32_Security",
    "Win32_Graphics",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D_Fxc",
    "Win32_Graphics_Direct3D_Dxc",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Direct2D",
    "Win32_UI",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
    "Win32_System_IO",
    "Win32_Storage_FileSystem",
    "Devices_Display_Core",
    "Graphics",
    "Graphics_DirectX",
    "Graphics_DirectX_Direct3D11",
]
